std = "lua51"
max_line_length = false
exclude_files = {
	"**/Libs",
}
only = {
	"011", -- syntax
	"1", -- globals
}
ignore = {
	"11/SLASH_.*", -- slash handlers
	"1/[A-Z][A-Z][A-Z0-9_]+", -- three letter+ constants
}
globals = {
	-- wow std api
	"abs",
	"acos",
	"asin",
	"atan",
	"atan2",
	"bit",
	"ceil",
	"cos",
	"date",
	"debuglocals",
	"debugprofilestart",
	"debugprofilestop",
	"debugstack",
	"deg",
	"difftime",
	"exp",
	"fastrandom",
	"floor",
	"forceinsecure",
	"foreach",
	"foreachi",
	"format",
	"frexp",
	"geterrorhandler",
	"getn",
	"gmatch",
	"gsub",
	"hooksecurefunc",
	"issecure",
	"issecurevariable",
	"ldexp",
	"log",
	"log10",
	"max",
	"min",
	"mod",
	"rad",
	"random",
	"scrub",
	"securecall",
	"seterrorhandler",
	"sin",
	"sort",
	"sqrt",
	"strbyte",
	"strchar",
	"strcmputf8i",
	"strconcat",
	"strfind",
	"string.join",
	"strjoin",
	"strlen",
	"strlenutf8",
	"strlower",
	"strmatch",
	"strrep",
	"strrev",
	"strsplit",
	"strsub",
	"strtrim",
	"strupper",
	"table.wipe",
	"tan",
	"time",
	"tinsert",
	"tremove",
	"wipe",


	-- everything else
	"GetBuildInfo",
	"AptechkaDefaultConfig",
	"AptechkaUserConfig",
	"AptechkaConfigMerged",
	"AptechkaConfigCustom",
	"Aptechka",

	"GetLocale",
	"Enum",
	"InterfaceOptionsFrame_OpenToCategory",
	"InterfaceOptions_AddCategory",
	"InterfaceOptionsFrame",
	"CompactRaidFrameManager",
	"CompactUnitFrameProfiles",
	"CopyTable",
	"ReloadUI",
	"GetTexCoordsForRoleSmallCircle",
	"GetReadyCheckStatus",
	"SetRaidTargetIconTexture",
	"GetRaidTargetIndex",


	"GetSpellTexture",
	"GetSpellInfo",
	"SpellGetVisibilityInfo",

	"LibStub",
	"Clique",

	"InitiateRolePoll",
	"C_IncomingSummon",
	"C_VoiceChat",
	"C_Map",
	"GetCVar",
	"SlashCmdList",
	"IsSpellInRange",
	"DebuffTypeColor",
	"UIParent",
	"UnitHasIncomingResurrection",
	"UnitAffectingCombat",
	"UnitHealth",
	"UnitHealthMax",
	"C_Timer",
    "LoadAddOn",
    "IsAddOnLoaded",
    "DisableAddOn",
    "EnableAddOn",
	"UnitHasVehicleUI",
    "UnitInVehicle",
    "UnitUsingVehicle",
    "UnitGetIncomingHeals",
    "UnitGetTotalAbsorbs",
    "UnitGetTotalHealAbsorbs",
    "GetSpecialization",
    "GetSpecializationInfo",
    "UnitIsGhost",
    "UnitInPhase",
    "UnitIsWarModePhased",
    "UnitIsAFK",
    "UnitIsConnected",
    "UnitPowerType",
    "SecureButton_GetModifiedUnit",
    "UnitStagger",
    "GetPartyAssignment",
    "UnitIsGroupLeader",
    "UnitIsGroupAssistant",
    "GetNumGroupMembers",
    "C_Timer",
    "ClickCastHeader",
    "SecureHandler_OnLoad",
    "UnitFrame_OnEnter",
    "UnitFrame_OnUpdate",
    "UnitFrame_OnLeave",
    "GetNumGroupMembers",
    "GetInstanceInfo",

	"UnitPower",
	"UnitPowerMax",
	"UnitAura",
	"UnitIsDeadOrGhost",
	"UnitExists",
	"UnitIsUnit",
	"UnitInRange",
	"UnitName",
	"GetRealmName",
	"UnitThreatSituation",
	"UnitGroupRolesAssigned",
	"UnitIsPlayer",
	"UnitPlayerControlled",
	"CombatLogGetCurrentEventInfo",
	"IsInGroup",
	"IsInInstance",
	"IsInRaid",
	"InCombatLockdown",
	"UnitIsPlayer",
	"UnitIsFriend",
	"GetTime",
	"CreateFrame",
	"UnitGUID",
	"oUF",
	"C_NamePlate",
	"UnitClass",
	"UnitIsTapDenied",
	"UnitReaction",
	"IsPlayerSpell",
	"GetShapeshiftForm",
}
